server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb01
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    password: samuel
  application:
    name: microservicecloud-provider-dept
# 通用mapper
mapper:
  mappers: com.offcn.mapper
  identity: mysql
  not-empty: false

logging:
  level:
     com.offcn.mapper : debug

# 将服务注册给注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-provider-dept:8001
    prefer-ip-address: true

info:
  app.name: offcn-microservicecloud
  company.name: www.offcn.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$











